# Generated by Django 5.0.1 on 2024-01-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('tables_or_single_seats', models.CharField(choices=[('Tables', 'Tables'), ('Single Seats', 'Single Seats')], default='Tables', max_length=20)),
                ('total_tables', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_seats', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
