# Generated by Django 5.0.1 on 2024-01-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat_allocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tables_or_single_seats',
            field=models.CharField(choices=[('Tables', 'Tables'), ('Single Seats', 'Single Seats')], default='Select an option', max_length=20),
        ),
    ]
